### ISSUE TITLE
Installing the chart ends up in Crashloopbackof

### ISSUE THREAD

**Issue by jcsaaddupuy** [camptocamp/helm-geoserver-cloud#114]
Hi,

First of all, I'm not sure if this is related to the Chart itself or the Geoserver service itself.
When installing the Chart following the instructions in the README, all the services ends up in error or CrashLoopBackOff - apparently caused by a configuration issue.

```
Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'org.geoserver.platform.GeoServerResourceLoader' available: expected at least 1 bean which qualifies as autowire candidate. 
```

We installed the chart on a k3d cluster but also on a GCP one with the same results.

```sh
$ kubectl create namespace geoserver
namespace/geoserver created

$helm dependency update

# install the chart in the namespace geoserver
$ helm install -n geoserver geoserver .

NAME: geoserver
LAST DEPLOYED: Fri Feb 17 09:48:13 2023
NAMESPACE: geoserver
STATUS: deployed
REVISION: 1
TEST SUITE: None


$ kubectl get pods -n geoserver
NAME                                               READY   STATUS             RESTARTS      AGE
geoserver-geoservercloud-gateway-c44998964-ss4g5   1/1     Running            0             86s
geoserver-geoservercloud-gwc-679549787-kf4dn       0/1     CrashLoopBackOff   3 (15s ago)   86s
geoserver-geoservercloud-rest-659544779f-nx98p     0/1     CrashLoopBackOff   3 (17s ago)   86s
geoserver-geoservercloud-wcs-694467fdc-d8m6h       0/1     CrashLoopBackOff   3 (12s ago)   86s
geoserver-geoservercloud-webui-698d599646-ff975    0/1     Error              3 (35s ago)   86s
geoserver-geoservercloud-wfs-68f95c45b-2gx7l       0/1     CrashLoopBackOff   3 (14s ago)   86s
geoserver-geoservercloud-wms-b59445c58-2lk2b       0/1     CrashLoopBackOff   3 (16s ago)   86s
geoserver-postgresql-0                             1/1     Running            0             86s
geoserver-rabbitmq-0                               
```

example backtraces : 
```
# for wms
$ kubectl logs -f geoserver-geoservercloud-wms-b59445c58-2lk2b -n geoserver
Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'org.geoserver.platform.GeoServerResourceLoader' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.raiseNoMatchingBeanFound(DefaultListableBeanFactory.java:1801)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1357)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1311)
        at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:887)
        at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:791)
        ... 137 more


# for wfs
$ kubectl logs -f geoserver-geoservercloud-wfs-68f95c45b-2gx7l -n geoserver
***************************
APPLICATION FAILED TO START
***************************

Description:

Parameter 0 of method dataDirectory in org.geoserver.cloud.config.catalog.backend.core.CoreBackendConfiguration required a bean of type 'org.geoserver.platform.GeoServerResourceLoader' that could not be found.


Action:

Consider defining a bean of type 'org.geoserver.platform.GeoServerResourceLoader' in your configuration.
```

I'm not sure how to fix the problem. What could be the root cause ?

Thanks in advance

**Comment by simon-fre** [comment]
We have encountered the same problem during the installation locally on Ubuntu 22.04.1 and on Azure in an AKS-Cluster.

Any help is highly appreciated! Thanks in advance.

**Comment by larsderidder** [comment]
We have the same issue. Looking forward to a possible solution. Happy to help test.

**Comment by l-soto** [comment]
I could not see even that the postgresql database is populated with the values of username, password and database for moving forward. Not even taking into consideration changing the defaults.

Template v0.0.49 (v0.1.0 does not even deploy postgresql)

(logs of the postgresql pod)
2023-03-14 12:44:23.616 GMT [837] FATAL:  password authentication failed for user "username"
2023-03-14 12:44:23.616 GMT [837] DETAIL:  Role "username" does not exist.
        Connection matched pg_hba.conf line 1: "host     all             all             0.0.0.0/0               md5"
2023-03-14 12:44:23.998 GMT [838] FATAL:  password authentication failed for user "username"
2023-03-14 12:44:23.998 GMT [838] DETAIL:  Role "username" does not exist.
        Connection matched pg_hba.conf line 1: "host     all             all             0.0.0.0/0               md5"

**Comment by audunsolemdal** [comment]
> 

I tried both versions today and came to the same conclusion. In 0.0.49 there does not seem to be a mapping between the default username/password/role and inputs to the dependent postgresql chart

**Comment by audunsolemdal** [comment]
Regarding postgresql, for 0.1.1 and onwards:

https://github.com/camptocamp/helm-geoserver-cloud/issues/119

**Comment by danduk82** [comment]
Hi all, please checkout the examples now that the chart has been refactored.
