### ISSUE TITLE
org.postgresql.util.PSQLException: ERROR: no schema has been selected while using db other than postgres.

### ISSUE THREAD

**Issue by 1ly1mk** [camptocamp/helm-geoserver-cloud#181]
Caused by: org.postgresql.util.PSQLException: ERROR: no schema has been selected to create in
  Position: 14
  at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2675) ~[postgresql-42.3.8.jar:42.3.8]
  at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2365) ~[postgresql-42.3.8.jar:42.3.8]
  at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:355) ~[postgresql-42.3.8.jar:42.3.8]
  at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:490) ~[postgresql-42.3.8.jar:42.3.8]
  at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:408) ~[postgresql-42.3.8.jar:42.3.8]
  at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:329) ~[postgresql-42.3.8.jar:42.3.8]
  at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:315) ~[postgresql-42.3.8.jar:42.3.8]
  at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:291) ~[postgresql-42.3.8.jar:42.3.8]
  at org.postgresql.jdbc.PgStatement.executeUpdate(PgStatement.java:265) ~[postgresql-42.3.8.jar:42.3.8]
  at com.zaxxer.hikari.pool.ProxyStatement.executeUpdate(ProxyStatement.java:119) ~[HikariCP-4.0.3.jar:na]
  at com.zaxxer.hikari.pool.HikariProxyStatement.executeUpdate(HikariProxyStatement.java) ~[HikariCP-4.0.3.jar:na]
  at org.springframework.jdbc.core.JdbcTemplate$1UpdateStatementCallback.doInStatement(JdbcTemplate.java:547) ~[spring-jdbc-5.3.31.jar:5.3.31]
  at org.springframework.jdbc.core.JdbcTemplate$1UpdateStatementCallback.doInStatement(JdbcTemplate.java:544) ~[spring-jdbc-5.3.31.jar:5.3.31]
  at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:383) ~[spring-jdbc-5.3.31.jar:5.3.31]
  ... 190 common frames omitted

This error is raised while using schema other than public with newly created db. This works fine if postgres db is used.

**Comment by 1ly1mk** [comment]
Fixed by providing owner to admin user on those schemas.
