### ISSUE TITLE
deployment issue

### ISSUE THREAD

**Issue by sgavathe** [camptocamp/helm-geoserver-cloud#49]
Hello,

I get the majority pods being CrashLoopBackOff

 kubectl get pods
```
NAME                                                READY   STATUS             RESTARTS         AGE
geoserver-postgresql-0                              1/1     Running            0                61m
geoserver-rabbitmq-0                                1/1     Running            0                61m
geoserver-geoservercloud-gateway-7c7b6d8dc9-l29t6   1/1     Running            0                61m
geoserver-geoservercloud-wfs-747bc6554b-6rwj4       0/1     CrashLoopBackOff   15 (5m3s ago)    61m
geoserver-geoservercloud-gwc-f8f96cb86-tvpct        0/1     CrashLoopBackOff   15 (4m55s ago)   61m
geoserver-geoservercloud-wcs-5cbbfc9b8-tdc9j        0/1     CrashLoopBackOff   15 (4m45s ago)   61m
geoserver-geoservercloud-webui-6998c8fd4-x7pp4      0/1     CrashLoopBackOff   13 (4m26s ago)   61m
geoserver-geoservercloud-wms-55bfbb6886-hh5cb       0/1     CrashLoopBackOff   15 (4m20s ago)   61m
geoserver-geoservercloud-rest-6fc974cc65-zrdd7      0/1     ImagePullBackOff   0                61m
geoserver-geoservercloud-wcs-6775b5d7db-vslh4       0/1     CrashLoopBackOff   6 (22s ago)      6m35s
```

And the reason being below, ( kubectl logs --previous --tail 10 geoserver-geoservercloud-wcs-6775b5d7db-vslh4)
       
   ```
at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)
Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'geoServerLoaderImpl' available
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeanDefinition(DefaultListableBeanFactory.java:872)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getMergedLocalBeanDefinition(AbstractBeanFactory.java:1344)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:309)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:283)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:322)
        ... 19 more
```

Thanks,

**Comment by sgavathe** [comment]
Sorry, was able to figure out what the issue was . It was the image reference that I was using wrong.

**Comment by illflavored** [comment]
I'm having a similar issue. @sgavathe what was the image reference change you made to resolve this?

**Comment by sgavathe** [comment]
@illflavored honesty, I followed the chart made by @danduk82 

This chart will helm you get started.
https://github.com/danduk82/helm-ogscloud

**Comment by ubiseli** [comment]
@sgavathe could you share more about how you solved this issue? I'm having the same problem and have not been able to make progress, even with @danduk82's chart (though not for a lack of trying).

Would really appreciate your input.
