### ISSUE TITLE
Error creating bean with name 'geoServerLoader'

### ISSUE THREAD

**Issue by stephgaz** [camptocamp/helm-geoserver-cloud#76]
Hi,

I'm trying to deploy your Helm chart in a K8S cluster. 

And For all services pod (webui, wms, ...), except gateway, I got this error: 

***************************
APPLICATION FAILED TO START
***************************

Description:

A component required a bean named 'geoServerLoaderImpl' that could not be found.

Action:

Consider defining a bean named 'geoServerLoaderImpl' in your configuration.

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'geoServerLoader' defined in class path resource [org/geoserver/cloud/config/catalog/CoreBackendConfiguration.class]: 'geoServerLoader' depends on missing bean 'geoServerLoaderImpl'; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'geoServerLoaderImpl' available
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:325)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:213)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.registerBeanPostProcessors(PostProcessorRegistrationDelegate.java:270)
	at org.springframework.context.support.AbstractApplicationContext.registerBeanPostProcessors(AbstractApplicationContext.java:762)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:567)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:145)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:740)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:415)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:303)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1312)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1301)
	at org.geoserver.cloud.web.app.WebUIApplication.main(WebUIApplication.java:20)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65)
Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'geoServerLoaderImpl' available
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeanDefinition(DefaultListableBeanFactory.java:872)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getMergedLocalBeanDefinition(AbstractBeanFactory.java:1344)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:309)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:283)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:322)
	... 19 more

Same result with 1.0-RC21 and 1.0-RC-22

Please help !

**Comment by danduk82** [comment]
Hello @stephgaz , this seems an application problem. Please report this issue on [geoserver-cloud project](https://github.com/geoserver/geoserver-cloud/issues) directly.
